# -*- coding: utf-8 -*-

PROVINCE_INLAND = 0
PROVINCE_COASTAL = 1
PROVINCE_WATER = 2

PROVINCE_TYPES = [PROVINCE_INLAND, 
                  PROVINCE_COASTAL, 
                  PROVINCE_WATER]

UNIT_ARMY = "Army"
UNIT_FLEET = "Fleet"

UNIT_TYPES = [UNIT_ARMY, UNIT_FLEET]

ORDER_HOLD = "Hold"
ORDER_MOVE = "Move"
ORDER_SUPPORT = "Support"
#ORDER_CONVOY = "Convoy"

ORDER_TYPES = [ORDER_HOLD, ORDER_MOVE, ORDER_SUPPORT]#, ORDER_CONVOY]

SPECIAL_SUPPLY = "Supply"

SPECIAL_PROVINCES = [SPECIAL_SUPPLY]

